name: Build and Dockerize Spring Boot App

on:
  push:
    branches:
      - main
      - staging
      - dev
  pull_request:

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - name: Cache Maven packages
        uses: actions/cache@v4
        with:
          path: ~/.m2
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-maven

      - name: Build with Maven
        run: mvn clean package --no-transfer-progress

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: Dockerfile
          push: true
          tags: gitauwairimu/messageboard:${{ github.sha }}

  updateKustomizeRepo:
    needs: build-and-push
    runs-on: ubuntu-latest

    steps:
      - name: Checkout GitOps repo
        uses: actions/checkout@v4
        with:
          repository: gitauwairimu/MessageBoardk8sRepo
          token: ${{ secrets.GH_TOKEN }}
          path: k8s-repo

      - name: Set up Kustomize
        uses: imranismail/setup-kustomize@v1

      - name: Determine overlay path
        id: overlay
        run: |
          if [[ "${{ github.ref }}" == "refs/heads/main" ]]; then
            echo "OVERLAY=prod" >> "$GITHUB_ENV"
          elif [[ "${{ github.ref }}" == "refs/heads/staging" ]]; then
            echo "OVERLAY=staging" >> "$GITHUB_ENV"
          elif [[ "${{ github.ref }}" == "refs/heads/dev" ]]; then
            echo "OVERLAY=dev" >> "$GITHUB_ENV"
          else
            echo "Unsupported branch: ${{ github.ref }}"
            exit 1
          fi

      - name: Update image tag in Kustomization
        run: |
          cd k8s-repo/kustomize/overlays/${{ env.OVERLAY }}
          kustomize edit set image gitauwairimu/messageboard=gitauwairimu/messageboard:${{ github.sha }}

      - name: Commit and push changes
        run: |
          cd k8s-repo
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git add kustomize/overlays/${{ env.OVERLAY }}/kustomization.yaml
          git commit -m "Update image for ${{ env.OVERLAY }} to ${{ github.sha }}"
          git push
